# Set site.output == "print-pdf"
output: "print-pdf"
# Set site.image-set == "images/print-pdf"
image-set: "images/print-pdf"
# Turn off documentation
collections:
  docs:
    output: false
exclude:
  # The usual excludes from _config.yml
  - run-linux.sh
  - run-mac.command
  - run-windows.bat
  - Gemfile
  - Gemfile.lock
  - README*
  - LICENSE*
  - CHANGELOG*
  - node_modules
  - eslint.json
  - gulpfile.js
  - package.json
  - package-lock.json
  - CNAME
  # Exclude files we don't need for print-pdf
  - search*
  - index*
  - /assets/*.jpg
  - /assets/js/accordion.js
  - /assets/js/annotation.js
  - /assets/js/elasticlunr-setup.js
  - /assets/js/elasticlunr.min.js
  - /assets/js/mark.min.js
  - /assets/js/mcqs.js
  - /assets/js/nav.js
  - /assets/js/render-search-index.js
  - /assets/js/search-engine.js
  - /assets/js/search-index.js
  - /assets/js/search-results.js
  - /assets/js/search-store.js
  - /assets/js/search-terms.js
  - /assets/js/videos.js
  - /*/package.opf
  - /*/toc.ncx
  - /*/styles/screen-pdf.scss
  - /*/styles/web.scss
  - /*/styles/epub.scss
  - /*/styles/app.scss
  - /*/index.md
  - /*/images/screen-pdf
  - /*/images/web
  - /*/images/epub
  - /*/images/app
# Temporarily exclude these and keep_files them below
# for faster builds where you don't need to refresh these.
  # - /assets/fonts
  # - /book/fonts
  # - /book/styles
# Populate the keep_files list for temporary faster builds
# or to keep previously generated files for other formats.
keep_files:
  # - assets/fonts
  # - book/fonts
  # - book/styles
